export const userStatusEnum = {
  FUNNEL_PENDING: 'FUNNEL_PENDING',
  IS_VERIFY_PENDING: 'IS_VERIFY_PENDING',
  ACTIVE: 'ACTIVE',
  INVALID_LOGIN_ATTEMPTS_RESTRICTION: 'INVALID_LOGIN_ATTEMPTS_RESTRICTION',
  DISABLE_BY_ADMINISTRATOR: 'DISABLE_BY_ADMINISTRATOR',
  EXPIRED: 'EXPIRED',
};

export const userRoleEnum = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BUYER: 'BUYER',
  SELLER: 'SELLER',
  BUYER_OR_SELLER: 'BUYER_OR_SELLER',
  TEMP_USER: 'TEMP_USER'
};
